# Obfuscated with PyObfuscate
# https://www.github.com/htr-tech
# Time : Thu Nov  9 18:20:00 2023
# -------------------------------
_ = lambda __ : __import__('marshal').loads(__import__('base64').b64decode(__[::-1]));exec((_)(b'AAAAHIHFAANFAANFAANFAANFAANFAANFAANFAgtPAAtPAQtPAEdPKAdCEKAgJAA2JAYCAmAgJAA2BEQADAPAAAQOzBAAAEAAAAQCy5TZsVHZv1GPIovP4xzA6DAAAAw8AkKAAAgAytETTNg2tVGdzl3cGo9cvJg2EkSduVWbEodApYDMwIjLulWTulmWn5WdB9SbvNmLr92biV2YhZmL3d3dv8iOzBHd0hGIuVGcv1yZkhXM65EAAAAApTQKAMVAkBQADo1AtJAbDQGAkBQAAAAAAAAAAAQArCAABYqAkBAAAAAAAAAABoGAlBgAAoFAsFAZAQGAXCAAAoz8AAAAAAAAAMAAAAAAAAAAAAAAAAwY'))